### ISSUE TITLE
Stepper current values

### ISSUE THREAD

**Issue by jhbeskow** [simcole/Wanhaoi3SKR1.4#3]
Hello,

I have been following your blog on this upgrade.  First off, thank you so much for posting!  It has been extremely helpful.  I have also been following the guide you originally followed.  The biggest different between the two is the stepper current.  I am still trying to figure out what to set that to.  As you noted, the other post sets his at a higher current than you do.  I have also been looking at the discussion in this thread that states the ratings for my motors are 1.2 and 1.3A: https://groups.google.com/g/wanhao-printer-3d/c/HlGk99Hm7e8/m/ImZ3bVN2DgAJ

My motors are:
X/Y/E: Moons C17HD40102-01N
Z: Moons C17HD6029-06N

I think this is the exact same setup that you have, but I am using 2208s instead of 2209s.  Would there be anything different there?  Have your current settings been working well so far?  Any issue with the dual Z motors on the same driver at the same current? 

Thank you again!

**Comment by simcole** [comment]
Hey Joel,
I'm glad you found the post helpful. I actually just did an upgrade to Marlin 2.0.7.2 and thought about updating the post again but I'm having a HORRIBLE time with UBL mesh.  I recently gave up on mesh completely and just went back to manual bed leveling.  My prints went from unusable to perfect again and I have no idea why mesh wouldn't work for me.  Anyway, I didn't answer your question.  I'm running 734 like I put in my post.  I've had ZERO issues and no noticeable heat issues either.  People usually report skipped stepps or rough prints when the voltage isn't high enough, but I haven't experienced that.  When I print, they don't feel hot to the touch either so I'm going to stick with 734.  Your motors look to be the same as mine.  If anything you could run higher voltages and see if it made a difference for you but feel your motors.  I'm attaching my latest config and config_adv.h so you can see what I did.  This is current as of last week.  I don't think there is a huge difference between 2208 and 2209 except stealthchop etc but you can look up those differences online.  I don't have any Z issues.  
Send back any questions or feedback on ways to improve the blog post you can.  Thanks.
Adam    On Tuesday, February 2, 2021, 11:42:54 AM EST, Joel Beskow <notifications@github.com> wrote:  
 
 


Hello,

I have been following your blog on this upgrade. First off, thank you so much for posting! It has been extremely helpful. I have also been following the guide you originally followed. The biggest different between the two is the stepper current. I am still trying to figure out what to set that to. As you noted, the other post sets his at a higher current than you do. I have also been looking at the discussion in this thread that states the ratings for my motors are 1.2 and 1.3A: https://groups.google.com/g/wanhao-printer-3d/c/HlGk99Hm7e8/m/ImZ3bVN2DgAJ

My motors are:
X/Y/E: Moons C17HD40102-01N
Z: Moons C17HD6029-06N

I think this is the exact same setup that you have, but I am using 2208s instead of 2209s. Would there be anything different there? Have your current settings been working well so far? Any issue with the dual Z motors on the same driver at the same current?

Thank you again!

**Comment by jhbeskow** [comment]
Thank you!  Oh no on bed leveling!  That was one of the features I was looking forward to the most.  When you say manual, do you just mean with the thumb screws?  If nothing else, I'm hoping to do Billinear.

I am not sure the file attached, but that's OK.  Two more quick questions.  Were you able to take the JST plugs for the thermistors exactly as they were on the stock board and plug directly into the SKR without any changes (swapping wires)?  I wasn't sure if I needed to swap the wire order based on what the old board showed.

Also, I haven't seen it spelled out anywhere on any the blogs I have followed.  Do you completely remove the current Z endstop?  I see that you had it plugged in, but from what I can tell, the BLTouch becomes the homing Z min.

**Comment by simcole** [comment]
Hey yes the files were attached to the last email. Maybe this got messed up since it was sent to GitHub. I’ll upload a config later this week. 

Yes manual back to thumb screws. I just got the paper close everywhere and it works great. UBL mesh was just a nightmare for me. I probably spent 30 hours diagnosing and trying to fix UBL and gave up when it didn’t work any better. Your mileage may vary. If you think your plate is really flat bi-linear might be ok. 

Yes the thermistor plugged right in as I recall. I do recall having to take an old DuPont wire and make a new end for one of the connectors but I’m not home to look at which one.  You shouldn’t have to swap any wires. 

I didn’t remove the Z end stop I just left it. BlTouch is my new end stop so it tells the printer when to stop.

**Comment by jhbeskow** [comment]
Thank you so much!  You have been incredibly helpful.
